### PR TITLE
Fixing missing rev_name in return dict of process_interleaved

### PR DESCRIPTION
**Pull request by samseaver**

### CODE REVIEW

**Comment by msneddon** [comment]
This seems like it would cause tests to break- do any have to be updated?

**Comment by samseaver** [comment]
I dont know, shouldn't tests have revealed this in the first place?

**Comment by MrCreosote** [comment]
It looks to me like the current behavior is what's intended. All three of the process_* (paired, interleaved, single) methods do the same thing and return the original file names, not the new file names (which are available from the path). That is specified in the documentation: https://github.com/kbaseapps/ReadsUtils/blob/master/ReadsUtils.spec#L194

If we were to make this change, no information would be added to the returned data structure, and the original names of the files would be lost. Additionally, the change must be made in all three methods that produce this type of output.

The tests do indeed cover the file names, and now fail due to these changes.

**Comment by samseaver** [comment]
OK, well, it threw an error because I was trying to call the filename of the de-interleaved files, and so, instead of being able to use

```rev_name=files['rev_name']```

I now use

```rev_name=files['rev'].split('/')[-1]```

But I thought this was a bug.

**Comment by MrCreosote** [comment]
I'd suggest `os.path.basename()` but yeah, that's the way to do it.

**Pull request closed without merging**
