### PR TITLE
using personal google account instead of edu account

### PR DESCRIPTION
**Pull request by Tianhao-Gu**

### CODE REVIEW

**Comment by Tianhao-Gu** [comment]
@MrCreosote @jkbaumohl getting lucky? tests all passed >_<

**Comment by MrCreosote** [comment]
Do you know why the institutional account doesn't work?

**Comment by Tianhao-Gu** [comment]
@MrCreosote hmmm I don't have a lot of clues.  There is an extra security setting saying `The organization's settings prevent changing this setting`. I am not sure what it means. But that's something I noticed is different than my personal google account.

**Review by MrCreosote — APPROVED** [review]
LGTM then

**Pull request merged**
