### PR TITLE
Merge new sdk build test & badging.

### PR DESCRIPTION
**Pull request by jsfillman**
Update to `README.md` to include build, coverage, and LGTM badging.

Since the CI & coverage portions are still a work in progress, this is a draft pull request for now.

### CODE REVIEW

**Comment by jsfillman** [comment]
Attempting merge of badging from previous project.

**Comment by MrCreosote** [comment]
The test logs seem to have expired already - is there anyway to keep them around?

**Comment by MrCreosote** [comment]
Is there any need for the travis run now that the full tests are run by actions? It seems like the travis build could be removed.

**Comment by jsfillman** [comment]
Removed redundant Travis build tests. Should be good to merge now.

**Comment by MrCreosote** [comment]
I'm pretty amazed the tests actually pass

**Comment by MrCreosote** [comment]
A couple other things I noticed:

**Comment by MrCreosote** [comment]
A couple other things I noticed:
1) LGTM should be configured to ignore `ReadsUtilsServer.py` since it's generated code. Having warnings against that doesn't make sense.
2) There's a coverage badge, but it doesn't seem there's any coverage set up. Should probably remove the badge for now, unless I'm missing something.

**Comment by jsfillman** [comment]
Testing with new CodeQL config to ignore `ReadsUtilsServer.py`.

The badging is intentionally boilerplate, so anything lacking is meant to be a reminder to add it.
I'm just trying to avoid causing extra stress by merging repos with passing build tests first.

**Pull request merged**
